name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: ./scripts/install_reqs.sh

    - name: Compile and run C++ tests (Release)
      run: ./scripts/rebuild.sh Release

    - name: Compile and run C++ tests (Debug)
      run: |
           ./scripts/rebuild.sh
           ./scripts/run_tests.sh

    - name: Check Python lint
      run: pytest --flake8 python/
