name: linux_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1

    - name: Install dependencies
      run: ./scripts/install_reqs.h
      shell: bash

    - name: Compile and run tests (Release)
      run: ./scripts/build.sh Release
      
    - name: Compile and run tests (Debug)
      run: |
           ./scripts/build.sh
           ./scripts/run_tests.sh
