name: linux_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_build:

    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Compile in Release
      run: MSBuild algo-trading\algo-trading.sln -m -p:Configuration=Release
      
    - name: Compile in Debug
      run: MSBuild algo-trading\algo-trading.sln -m
