name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Compile in Debug
      shell: cmd
      run: .\scripts\win\build.bat

    - name: Compile in Release
      shell: cmd
      run: .\scripts\win\buid.bat RelWithDebInfo

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: trading_binaries
        path: |
          build\src\trading\trading.exe
          build\src\trading\trading.pdb
          build\src\trading\trading.ilk
