name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Compile binaries
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        md build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "NMake Makefiles" ..\cpp ..\build
        nmake

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: trading_binaries
        path: build/package/*
